// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVLsohmyaT8Jrst_LVSzTxa7NEJAtqgE',
    appId: '1:754154797926:web:a85527f49c9eaa55c566a7',
    messagingSenderId: '754154797926',
    projectId: 'finishd-app',
    authDomain: 'finishd-app.firebaseapp.com',
    storageBucket: 'finishd-app.firebasestorage.app',
    measurementId: 'G-BC55HW92J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXknlItBBvd5JpXZcLfRJK90n_1fNNpVQ',
    appId: '1:754154797926:android:65e18af125903904c566a7',
    messagingSenderId: '754154797926',
    projectId: 'finishd-app',
    storageBucket: 'finishd-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_7nqvjTEQekDGlN2e0bOv3Z9jI4-J8I',
    appId: '1:754154797926:ios:9aac735ada073200c566a7',
    messagingSenderId: '754154797926',
    projectId: 'finishd-app',
    storageBucket: 'finishd-app.firebasestorage.app',
    androidClientId: '754154797926-ikoq7rbsre3av2eb6jbhmk6jf5fkbo2m.apps.googleusercontent.com',
    iosClientId: '754154797926-oriaveehob8kv66komutqsc61euhu3qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.finishd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_7nqvjTEQekDGlN2e0bOv3Z9jI4-J8I',
    appId: '1:754154797926:ios:9aac735ada073200c566a7',
    messagingSenderId: '754154797926',
    projectId: 'finishd-app',
    storageBucket: 'finishd-app.firebasestorage.app',
    androidClientId: '754154797926-ikoq7rbsre3av2eb6jbhmk6jf5fkbo2m.apps.googleusercontent.com',
    iosClientId: '754154797926-oriaveehob8kv66komutqsc61euhu3qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.finishd',
  );

}