// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/objectbox/chat_entities.dart';
import 'db/objectbox/feed_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7229925374468275782),
      name: 'SeenItem',
      lastPropertyId: const obx_int.IdUid(7, 3933606902895287817),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3703854749306802216),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 536096821680769858),
            name: 'itemId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 4803534543321528267)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1224035866487339195),
            name: 'seenAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8036585211454583561),
            name: 'suppressed',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1695917865872719141),
            name: 'lastSeenAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4814002446751723000),
            name: 'viewDurationMs',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3933606902895287817),
            name: 'liked',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 5898609316714232361),
      name: 'LocalConversation',
      lastPropertyId: const obx_int.IdUid(14, 5808113675719174907),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7121095485274841134),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4484027024310292286),
            name: 'firestoreId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(4, 3906381599556492607)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9152551853944956835),
            name: 'participantsJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6808463861761287229),
            name: 'lastMessageText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 558080672317823673),
            name: 'lastMessageType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2732672898980603055),
            name: 'lastMessageSenderId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5408095849447728150),
            name: 'lastMessageAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4768231950188287366),
            name: 'lastSyncedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1498921646435197669),
            name: 'unreadCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4348944910948148500),
            name: 'isGroup',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6350644550523687297),
            name: 'groupName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8847408169455362904),
            name: 'groupImageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6052819395793178590),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5808113675719174907),
            name: 'participants',
            type: 30,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 3586160544059811964),
      name: 'LocalMessage',
      lastPropertyId: const obx_int.IdUid(26, 2620960402803030156),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8064968720767321291),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 443959914094702004),
            name: 'firestoreId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 339998508385256544),
            name: 'conversationId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 4892426888363789072)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2156894154906857347),
            name: 'senderId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8594266727301572396),
            name: 'receiverId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2725723622052003666),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8499259079060033794),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6543571654791382228),
            name: 'mediaUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 468476358281745490),
            name: 'movieId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8671369773825475579),
            name: 'movieTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3300423133220963876),
            name: 'moviePoster',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 763512357333980527),
            name: 'mediaType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6586519840644753567),
            name: 'videoId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4552599511967380305),
            name: 'videoTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 8410658147335075965),
            name: 'videoThumbnail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1152635275466891156),
            name: 'videoChannel',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1987228158509835804),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 559861863027195003),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 4324812335190970693),
            name: 'retryCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 4741967198628343439),
            name: 'isPending',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 104777825775197555),
            name: 'isRead',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 5083317677523967902),
            name: 'postId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 6697287315143650845),
            name: 'postContent',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 1682177965198923815),
            name: 'postAuthorName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 178077339641931552),
            name: 'postShowTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 2620960402803030156),
            name: 'showId',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 2196388408067714446),
      name: 'LocalParticipant',
      lastPropertyId: const obx_int.IdUid(8, 3246253778674633305),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9022432052807672200),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7332254250201174398),
            name: 'conversationId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(6, 1656900575815390775)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3750619337453923233),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2042701002324135580),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3674886355062323012),
            name: 'profileImage',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8595664106130122670),
            name: 'lastSeenAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2499077191937884905),
            name: 'isTyping',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3246253778674633305),
            name: 'isOnline',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 2876239502257983497),
      name: 'PendingMessageQueue',
      lastPropertyId: const obx_int.IdUid(5, 7096231345594461174),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6318398943961923833),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 945570654918069425),
            name: 'messageLocalId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5039571534900134916),
            name: 'queuedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8961130639399892848),
            name: 'retryCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7096231345594461174),
            name: 'lastError',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 3951725673702315505),
      name: 'FeedItemMeta',
      lastPropertyId: const obx_int.IdUid(4, 6966818340164713914),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4990755812415188729),
            name: 'localId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 478053237296806941),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(8, 3252746451004809340)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5647671737585716655),
            name: 'publishedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6966818340164713914),
            name: 'baseScore',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(9, 3951725673702315505),
      lastIndexId: const obx_int.IdUid(8, 3252746451004809340),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        6259640920451398742,
        2305464559775899733,
        195582632628087964
      ],
      retiredIndexUids: const [5050873118745731097],
      retiredPropertyUids: const [
        4136116018475878467,
        8291203067061176426,
        3138280338164359794,
        8590276416066245538,
        9020811007297669510,
        5184114814123524714,
        9020389057621037387,
        7998383011909362008,
        1610266952036725798,
        3268485935260837401,
        8523805696224982320,
        5278573601173417051,
        8214048009090720490,
        7996873072210705209,
        2030110448348204875,
        6265441929106783762,
        292365231786896847,
        1965774991035548976,
        1994003507970201802,
        3201059551979247326,
        4301067571903412515,
        4234103317627870858,
        7119203931168175594,
        956065914174313094,
        1472262738250591875,
        6966689232468569380,
        6541873968033022058,
        195713887359034703,
        1484071192511307047,
        4817454813962239214,
        1769285649005596844,
        1210924337403377674,
        2241293413637272079,
        6615221941200064135,
        2062157947869744104,
        4269811279036171550,
        7780718996706113705,
        5270207633331972996,
        746354880702542573,
        8084142039131415366,
        6133302295962675270,
        3779814504332354261,
        7201811634293036176
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SeenItem: obx_int.EntityDefinition<SeenItem>(
        model: _entities[0],
        toOneRelations: (SeenItem object) => [],
        toManyRelations: (SeenItem object) => {},
        getId: (SeenItem object) => object.localId,
        setId: (SeenItem object, int id) {
          object.localId = id;
        },
        objectToFB: (SeenItem object, fb.Builder fbb) {
          final itemIdOffset = fbb.writeString(object.itemId);
          fbb.startTable(8);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, itemIdOffset);
          fbb.addInt64(2, object.seenAt.millisecondsSinceEpoch);
          fbb.addBool(3, object.suppressed);
          fbb.addInt64(4, object.lastSeenAt.millisecondsSinceEpoch);
          fbb.addInt64(5, object.viewDurationMs);
          fbb.addBool(6, object.liked);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final itemIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final seenAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final lastSeenAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final viewDurationMsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final likedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final suppressedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = SeenItem(
              itemId: itemIdParam,
              seenAt: seenAtParam,
              lastSeenAt: lastSeenAtParam,
              viewDurationMs: viewDurationMsParam,
              liked: likedParam,
              suppressed: suppressedParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    LocalConversation: obx_int.EntityDefinition<LocalConversation>(
        model: _entities[1],
        toOneRelations: (LocalConversation object) => [],
        toManyRelations: (LocalConversation object) => {},
        getId: (LocalConversation object) => object.localId,
        setId: (LocalConversation object, int id) {
          object.localId = id;
        },
        objectToFB: (LocalConversation object, fb.Builder fbb) {
          final firestoreIdOffset = fbb.writeString(object.firestoreId);
          final participantsJsonOffset =
              fbb.writeString(object.participantsJson);
          final lastMessageTextOffset = object.lastMessageText == null
              ? null
              : fbb.writeString(object.lastMessageText!);
          final lastMessageTypeOffset = object.lastMessageType == null
              ? null
              : fbb.writeString(object.lastMessageType!);
          final lastMessageSenderIdOffset = object.lastMessageSenderId == null
              ? null
              : fbb.writeString(object.lastMessageSenderId!);
          final groupNameOffset = object.groupName == null
              ? null
              : fbb.writeString(object.groupName!);
          final groupImageUrlOffset = object.groupImageUrl == null
              ? null
              : fbb.writeString(object.groupImageUrl!);
          final participantsOffset = fbb.writeList(
              object.participants.map(fbb.writeString).toList(growable: false));
          fbb.startTable(15);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, firestoreIdOffset);
          fbb.addOffset(2, participantsJsonOffset);
          fbb.addOffset(3, lastMessageTextOffset);
          fbb.addOffset(4, lastMessageTypeOffset);
          fbb.addOffset(5, lastMessageSenderIdOffset);
          fbb.addInt64(6, object.lastMessageAt?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.lastSyncedAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.unreadCount);
          fbb.addBool(9, object.isGroup);
          fbb.addOffset(10, groupNameOffset);
          fbb.addOffset(11, groupImageUrlOffset);
          fbb.addInt64(12, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(13, participantsOffset);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastMessageAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final firestoreIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final participantsJsonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final lastMessageTextParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final lastMessageTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final lastMessageSenderIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final lastMessageAtParam = lastMessageAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastMessageAtValue);
          final lastSyncedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final unreadCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final isGroupParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final groupNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final groupImageUrlParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0));
          final object = LocalConversation(
              firestoreId: firestoreIdParam,
              participantsJson: participantsJsonParam,
              lastMessageText: lastMessageTextParam,
              lastMessageType: lastMessageTypeParam,
              lastMessageSenderId: lastMessageSenderIdParam,
              lastMessageAt: lastMessageAtParam,
              lastSyncedAt: lastSyncedAtParam,
              unreadCount: unreadCountParam,
              isGroup: isGroupParam,
              groupName: groupNameParam,
              groupImageUrl: groupImageUrlParam,
              createdAt: createdAtParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..participants = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 30, []);

          return object;
        }),
    LocalMessage: obx_int.EntityDefinition<LocalMessage>(
        model: _entities[2],
        toOneRelations: (LocalMessage object) => [],
        toManyRelations: (LocalMessage object) => {},
        getId: (LocalMessage object) => object.localId,
        setId: (LocalMessage object, int id) {
          object.localId = id;
        },
        objectToFB: (LocalMessage object, fb.Builder fbb) {
          final firestoreIdOffset = object.firestoreId == null
              ? null
              : fbb.writeString(object.firestoreId!);
          final conversationIdOffset = fbb.writeString(object.conversationId);
          final senderIdOffset = fbb.writeString(object.senderId);
          final receiverIdOffset = object.receiverId == null
              ? null
              : fbb.writeString(object.receiverId!);
          final contentOffset = fbb.writeString(object.content);
          final typeOffset = fbb.writeString(object.type);
          final mediaUrlOffset = object.mediaUrl == null
              ? null
              : fbb.writeString(object.mediaUrl!);
          final movieIdOffset =
              object.movieId == null ? null : fbb.writeString(object.movieId!);
          final movieTitleOffset = object.movieTitle == null
              ? null
              : fbb.writeString(object.movieTitle!);
          final moviePosterOffset = object.moviePoster == null
              ? null
              : fbb.writeString(object.moviePoster!);
          final mediaTypeOffset = object.mediaType == null
              ? null
              : fbb.writeString(object.mediaType!);
          final videoIdOffset =
              object.videoId == null ? null : fbb.writeString(object.videoId!);
          final videoTitleOffset = object.videoTitle == null
              ? null
              : fbb.writeString(object.videoTitle!);
          final videoThumbnailOffset = object.videoThumbnail == null
              ? null
              : fbb.writeString(object.videoThumbnail!);
          final videoChannelOffset = object.videoChannel == null
              ? null
              : fbb.writeString(object.videoChannel!);
          final postIdOffset =
              object.postId == null ? null : fbb.writeString(object.postId!);
          final postContentOffset = object.postContent == null
              ? null
              : fbb.writeString(object.postContent!);
          final postAuthorNameOffset = object.postAuthorName == null
              ? null
              : fbb.writeString(object.postAuthorName!);
          final postShowTitleOffset = object.postShowTitle == null
              ? null
              : fbb.writeString(object.postShowTitle!);
          fbb.startTable(27);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, firestoreIdOffset);
          fbb.addOffset(2, conversationIdOffset);
          fbb.addOffset(3, senderIdOffset);
          fbb.addOffset(4, receiverIdOffset);
          fbb.addOffset(5, contentOffset);
          fbb.addOffset(6, typeOffset);
          fbb.addOffset(7, mediaUrlOffset);
          fbb.addOffset(8, movieIdOffset);
          fbb.addOffset(9, movieTitleOffset);
          fbb.addOffset(10, moviePosterOffset);
          fbb.addOffset(11, mediaTypeOffset);
          fbb.addOffset(12, videoIdOffset);
          fbb.addOffset(13, videoTitleOffset);
          fbb.addOffset(14, videoThumbnailOffset);
          fbb.addOffset(15, videoChannelOffset);
          fbb.addInt64(16, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(17, object.status);
          fbb.addInt64(18, object.retryCount);
          fbb.addBool(19, object.isPending);
          fbb.addBool(20, object.isRead);
          fbb.addOffset(21, postIdOffset);
          fbb.addOffset(22, postContentOffset);
          fbb.addOffset(23, postAuthorNameOffset);
          fbb.addOffset(24, postShowTitleOffset);
          fbb.addInt64(25, object.showId);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final firestoreIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final conversationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final senderIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final receiverIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final mediaUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final movieIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final movieTitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final moviePosterParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final mediaTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final videoIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final videoTitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final videoThumbnailParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final videoChannelParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 34);
          final postIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 46);
          final postContentParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 48);
          final postAuthorNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final postShowTitleParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 52);
          final showIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 54);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0));
          final statusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          final retryCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 40, 0);
          final isPendingParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 42, false);
          final isReadParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 44, false);
          final object = LocalMessage(
              firestoreId: firestoreIdParam,
              conversationId: conversationIdParam,
              senderId: senderIdParam,
              receiverId: receiverIdParam,
              content: contentParam,
              type: typeParam,
              mediaUrl: mediaUrlParam,
              movieId: movieIdParam,
              movieTitle: movieTitleParam,
              moviePoster: moviePosterParam,
              mediaType: mediaTypeParam,
              videoId: videoIdParam,
              videoTitle: videoTitleParam,
              videoThumbnail: videoThumbnailParam,
              videoChannel: videoChannelParam,
              postId: postIdParam,
              postContent: postContentParam,
              postAuthorName: postAuthorNameParam,
              postShowTitle: postShowTitleParam,
              showId: showIdParam,
              createdAt: createdAtParam,
              status: statusParam,
              retryCount: retryCountParam,
              isPending: isPendingParam,
              isRead: isReadParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    LocalParticipant: obx_int.EntityDefinition<LocalParticipant>(
        model: _entities[3],
        toOneRelations: (LocalParticipant object) => [],
        toManyRelations: (LocalParticipant object) => {},
        getId: (LocalParticipant object) => object.localId,
        setId: (LocalParticipant object, int id) {
          object.localId = id;
        },
        objectToFB: (LocalParticipant object, fb.Builder fbb) {
          final conversationIdOffset = fbb.writeString(object.conversationId);
          final uidOffset = fbb.writeString(object.uid);
          final usernameOffset = fbb.writeString(object.username);
          final profileImageOffset = object.profileImage == null
              ? null
              : fbb.writeString(object.profileImage!);
          fbb.startTable(9);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, conversationIdOffset);
          fbb.addOffset(2, uidOffset);
          fbb.addOffset(3, usernameOffset);
          fbb.addOffset(4, profileImageOffset);
          fbb.addInt64(5, object.lastSeenAt?.millisecondsSinceEpoch);
          fbb.addBool(6, object.isTyping);
          fbb.addBool(7, object.isOnline);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastSeenAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final conversationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final profileImageParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final lastSeenAtParam = lastSeenAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastSeenAtValue);
          final isTypingParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final isOnlineParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final object = LocalParticipant(
              conversationId: conversationIdParam,
              uid: uidParam,
              username: usernameParam,
              profileImage: profileImageParam,
              lastSeenAt: lastSeenAtParam,
              isTyping: isTypingParam,
              isOnline: isOnlineParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    PendingMessageQueue: obx_int.EntityDefinition<PendingMessageQueue>(
        model: _entities[4],
        toOneRelations: (PendingMessageQueue object) => [],
        toManyRelations: (PendingMessageQueue object) => {},
        getId: (PendingMessageQueue object) => object.localId,
        setId: (PendingMessageQueue object, int id) {
          object.localId = id;
        },
        objectToFB: (PendingMessageQueue object, fb.Builder fbb) {
          final lastErrorOffset = object.lastError == null
              ? null
              : fbb.writeString(object.lastError!);
          fbb.startTable(6);
          fbb.addInt64(0, object.localId);
          fbb.addInt64(1, object.messageLocalId);
          fbb.addInt64(2, object.queuedAt.millisecondsSinceEpoch);
          fbb.addInt64(3, object.retryCount);
          fbb.addOffset(4, lastErrorOffset);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final messageLocalIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final queuedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final retryCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final lastErrorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final object = PendingMessageQueue(
              messageLocalId: messageLocalIdParam,
              queuedAt: queuedAtParam,
              retryCount: retryCountParam,
              lastError: lastErrorParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    FeedItemMeta: obx_int.EntityDefinition<FeedItemMeta>(
        model: _entities[5],
        toOneRelations: (FeedItemMeta object) => [],
        toManyRelations: (FeedItemMeta object) => {},
        getId: (FeedItemMeta object) => object.localId,
        setId: (FeedItemMeta object, int id) {
          object.localId = id;
        },
        objectToFB: (FeedItemMeta object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          fbb.startTable(5);
          fbb.addInt64(0, object.localId);
          fbb.addOffset(1, idOffset);
          fbb.addInt64(2, object.publishedAt.millisecondsSinceEpoch);
          fbb.addFloat64(3, object.baseScore);
          fbb.finish(fbb.endTable());
          return object.localId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final publishedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final baseScoreParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = FeedItemMeta(
              id: idParam,
              publishedAt: publishedAtParam,
              baseScore: baseScoreParam)
            ..localId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SeenItem] entity fields to define ObjectBox queries.
class SeenItem_ {
  /// see [SeenItem.localId]
  static final localId =
      obx.QueryIntegerProperty<SeenItem>(_entities[0].properties[0]);

  /// see [SeenItem.itemId]
  static final itemId =
      obx.QueryStringProperty<SeenItem>(_entities[0].properties[1]);

  /// see [SeenItem.seenAt]
  static final seenAt =
      obx.QueryDateProperty<SeenItem>(_entities[0].properties[2]);

  /// see [SeenItem.suppressed]
  static final suppressed =
      obx.QueryBooleanProperty<SeenItem>(_entities[0].properties[3]);

  /// see [SeenItem.lastSeenAt]
  static final lastSeenAt =
      obx.QueryDateProperty<SeenItem>(_entities[0].properties[4]);

  /// see [SeenItem.viewDurationMs]
  static final viewDurationMs =
      obx.QueryIntegerProperty<SeenItem>(_entities[0].properties[5]);

  /// see [SeenItem.liked]
  static final liked =
      obx.QueryBooleanProperty<SeenItem>(_entities[0].properties[6]);
}

/// [LocalConversation] entity fields to define ObjectBox queries.
class LocalConversation_ {
  /// see [LocalConversation.localId]
  static final localId =
      obx.QueryIntegerProperty<LocalConversation>(_entities[1].properties[0]);

  /// see [LocalConversation.firestoreId]
  static final firestoreId =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[1]);

  /// see [LocalConversation.participantsJson]
  static final participantsJson =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[2]);

  /// see [LocalConversation.lastMessageText]
  static final lastMessageText =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[3]);

  /// see [LocalConversation.lastMessageType]
  static final lastMessageType =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[4]);

  /// see [LocalConversation.lastMessageSenderId]
  static final lastMessageSenderId =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[5]);

  /// see [LocalConversation.lastMessageAt]
  static final lastMessageAt =
      obx.QueryDateProperty<LocalConversation>(_entities[1].properties[6]);

  /// see [LocalConversation.lastSyncedAt]
  static final lastSyncedAt =
      obx.QueryDateProperty<LocalConversation>(_entities[1].properties[7]);

  /// see [LocalConversation.unreadCount]
  static final unreadCount =
      obx.QueryIntegerProperty<LocalConversation>(_entities[1].properties[8]);

  /// see [LocalConversation.isGroup]
  static final isGroup =
      obx.QueryBooleanProperty<LocalConversation>(_entities[1].properties[9]);

  /// see [LocalConversation.groupName]
  static final groupName =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[10]);

  /// see [LocalConversation.groupImageUrl]
  static final groupImageUrl =
      obx.QueryStringProperty<LocalConversation>(_entities[1].properties[11]);

  /// see [LocalConversation.createdAt]
  static final createdAt =
      obx.QueryDateProperty<LocalConversation>(_entities[1].properties[12]);

  /// see [LocalConversation.participants]
  static final participants = obx.QueryStringVectorProperty<LocalConversation>(
      _entities[1].properties[13]);
}

/// [LocalMessage] entity fields to define ObjectBox queries.
class LocalMessage_ {
  /// see [LocalMessage.localId]
  static final localId =
      obx.QueryIntegerProperty<LocalMessage>(_entities[2].properties[0]);

  /// see [LocalMessage.firestoreId]
  static final firestoreId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[1]);

  /// see [LocalMessage.conversationId]
  static final conversationId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[2]);

  /// see [LocalMessage.senderId]
  static final senderId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[3]);

  /// see [LocalMessage.receiverId]
  static final receiverId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[4]);

  /// see [LocalMessage.content]
  static final content =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[5]);

  /// see [LocalMessage.type]
  static final type =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[6]);

  /// see [LocalMessage.mediaUrl]
  static final mediaUrl =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[7]);

  /// see [LocalMessage.movieId]
  static final movieId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[8]);

  /// see [LocalMessage.movieTitle]
  static final movieTitle =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[9]);

  /// see [LocalMessage.moviePoster]
  static final moviePoster =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[10]);

  /// see [LocalMessage.mediaType]
  static final mediaType =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[11]);

  /// see [LocalMessage.videoId]
  static final videoId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[12]);

  /// see [LocalMessage.videoTitle]
  static final videoTitle =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[13]);

  /// see [LocalMessage.videoThumbnail]
  static final videoThumbnail =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[14]);

  /// see [LocalMessage.videoChannel]
  static final videoChannel =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[15]);

  /// see [LocalMessage.createdAt]
  static final createdAt =
      obx.QueryDateProperty<LocalMessage>(_entities[2].properties[16]);

  /// see [LocalMessage.status]
  static final status =
      obx.QueryIntegerProperty<LocalMessage>(_entities[2].properties[17]);

  /// see [LocalMessage.retryCount]
  static final retryCount =
      obx.QueryIntegerProperty<LocalMessage>(_entities[2].properties[18]);

  /// see [LocalMessage.isPending]
  static final isPending =
      obx.QueryBooleanProperty<LocalMessage>(_entities[2].properties[19]);

  /// see [LocalMessage.isRead]
  static final isRead =
      obx.QueryBooleanProperty<LocalMessage>(_entities[2].properties[20]);

  /// see [LocalMessage.postId]
  static final postId =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[21]);

  /// see [LocalMessage.postContent]
  static final postContent =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[22]);

  /// see [LocalMessage.postAuthorName]
  static final postAuthorName =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[23]);

  /// see [LocalMessage.postShowTitle]
  static final postShowTitle =
      obx.QueryStringProperty<LocalMessage>(_entities[2].properties[24]);

  /// see [LocalMessage.showId]
  static final showId =
      obx.QueryIntegerProperty<LocalMessage>(_entities[2].properties[25]);
}

/// [LocalParticipant] entity fields to define ObjectBox queries.
class LocalParticipant_ {
  /// see [LocalParticipant.localId]
  static final localId =
      obx.QueryIntegerProperty<LocalParticipant>(_entities[3].properties[0]);

  /// see [LocalParticipant.conversationId]
  static final conversationId =
      obx.QueryStringProperty<LocalParticipant>(_entities[3].properties[1]);

  /// see [LocalParticipant.uid]
  static final uid =
      obx.QueryStringProperty<LocalParticipant>(_entities[3].properties[2]);

  /// see [LocalParticipant.username]
  static final username =
      obx.QueryStringProperty<LocalParticipant>(_entities[3].properties[3]);

  /// see [LocalParticipant.profileImage]
  static final profileImage =
      obx.QueryStringProperty<LocalParticipant>(_entities[3].properties[4]);

  /// see [LocalParticipant.lastSeenAt]
  static final lastSeenAt =
      obx.QueryDateProperty<LocalParticipant>(_entities[3].properties[5]);

  /// see [LocalParticipant.isTyping]
  static final isTyping =
      obx.QueryBooleanProperty<LocalParticipant>(_entities[3].properties[6]);

  /// see [LocalParticipant.isOnline]
  static final isOnline =
      obx.QueryBooleanProperty<LocalParticipant>(_entities[3].properties[7]);
}

/// [PendingMessageQueue] entity fields to define ObjectBox queries.
class PendingMessageQueue_ {
  /// see [PendingMessageQueue.localId]
  static final localId =
      obx.QueryIntegerProperty<PendingMessageQueue>(_entities[4].properties[0]);

  /// see [PendingMessageQueue.messageLocalId]
  static final messageLocalId =
      obx.QueryIntegerProperty<PendingMessageQueue>(_entities[4].properties[1]);

  /// see [PendingMessageQueue.queuedAt]
  static final queuedAt =
      obx.QueryDateProperty<PendingMessageQueue>(_entities[4].properties[2]);

  /// see [PendingMessageQueue.retryCount]
  static final retryCount =
      obx.QueryIntegerProperty<PendingMessageQueue>(_entities[4].properties[3]);

  /// see [PendingMessageQueue.lastError]
  static final lastError =
      obx.QueryStringProperty<PendingMessageQueue>(_entities[4].properties[4]);
}

/// [FeedItemMeta] entity fields to define ObjectBox queries.
class FeedItemMeta_ {
  /// see [FeedItemMeta.localId]
  static final localId =
      obx.QueryIntegerProperty<FeedItemMeta>(_entities[5].properties[0]);

  /// see [FeedItemMeta.id]
  static final id =
      obx.QueryStringProperty<FeedItemMeta>(_entities[5].properties[1]);

  /// see [FeedItemMeta.publishedAt]
  static final publishedAt =
      obx.QueryDateProperty<FeedItemMeta>(_entities[5].properties[2]);

  /// see [FeedItemMeta.baseScore]
  static final baseScore =
      obx.QueryDoubleProperty<FeedItemMeta>(_entities[5].properties[3]);
}
