import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import '../../objectbox.g.dart'; // Generated by build_runner

/// Global ObjectBox store singleton.
///
/// Initialize ONCE in main.dart before runApp():
/// await ObjectBoxStore.create();
class ObjectBoxStore {
  static ObjectBoxStore? _instance;
  late final Store store;

  ObjectBoxStore._create(this.store);

  /// Create and initialize the ObjectBox store.
  ///
  /// Must be called before accessing [instance].
  static Future<ObjectBoxStore> create() async {
    if (_instance != null) return _instance!;

    final docsDir = await getApplicationDocumentsDirectory();
    final store = await openStore(
      directory: p.join(docsDir.path, 'finishd_objectbox'),
    );

    _instance = ObjectBoxStore._create(store);
    return _instance!;
  }

  /// Get the singleton instance.
  ///
  /// Throws if [create] hasn't been called.
  static ObjectBoxStore get instance {
    if (_instance == null) {
      throw StateError('ObjectBoxStore not initialized. Call create() first.');
    }
    return _instance!;
  }

  /// Check if the store has been initialized.
  static bool get isInitialized => _instance != null;

  /// Close the store (for cleanup).
  void close() {
    store.close();
    _instance = null;
  }
}
